/*******************************************************************************
 * Copyright (c) 2023 Gradle Inc. and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 ******************************************************************************/
import org.gradle.util.GradleVersion

if (GradleVersion.current() >= GradleVersion.version("8.8")) {
    gradle.lifecycle.beforeProject { project ->
        project.apply plugin: "eclipse"
    }
} else {
    gradle.allprojects { project ->
        project.apply plugin: "eclipse"
    }
}